# Generated by Django 5.1.3 on 2024-12-16 12:32

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(help_text="Введите название статьи", max_length=255, verbose_name="Заголовок"),
                ),
                ("slug", models.SlugField(max_length=255, unique=True, verbose_name="Slug")),
                ("content", models.TextField(blank=True, verbose_name="Текст блога")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите изображение для превью",
                        null=True,
                        upload_to="BlogHaven/preview",
                        verbose_name="Превью",
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True, verbose_name="Дата создания")),
                (
                    "is_published",
                    models.BooleanField(choices=[(0, "Не опубликовано"), (1, "Опубликовано")], default=1),
                ),
                (
                    "view_counter",
                    models.PositiveIntegerField(
                        default=0, help_text="Укажите количество просмотров", verbose_name="Счетчик просмотров"
                    ),
                ),
            ],
            managers=[
                ("published", django.db.models.manager.Manager()),
            ],
        ),
    ]
