# Generated by Django 5.1.3 on 2024-12-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BlogHaven", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="blog",
            managers=[],
        ),
        migrations.AddField(
            model_name="blog",
            name="is_notification_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="blog",
            name="is_published",
            field=models.BooleanField(
                choices=[(0, "Не опубликовано"), (1, "Опубликовано")], default=1, verbose_name="Статус Публикации"
            ),
        ),
    ]
