# Generated by Django 5.1.3 on 2025-01-07 16:15

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("BlogHaven", "0002_alter_blog_managers_blog_is_notification_sent_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={"ordering": ["view_counter"], "verbose_name": "Статья", "verbose_name_plural": "Статьи"},
        ),
        migrations.AlterModelManagers(
            name="blog",
            managers=[
                ("published", django.db.models.manager.Manager()),
            ],
        ),
    ]
