# Generated by Django 5.1.3 on 2025-01-15 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("BlogHaven", "0003_alter_blog_options_alter_blog_managers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "ordering": ["view_counter"],
                "permissions": [("can_publish_post", "can publish post")],
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
            },
        ),
    ]
