# Generated by Django 5.1.3 on 2024-11-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(help_text="Введите контактное имя", max_length=150, verbose_name="Имя для связи"),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Введите контактный номер", max_length=16, verbose_name="Номер для связи"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Введите свою контактную почту", max_length=254, verbose_name="Почта для связи"
                    ),
                ),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
                "ordering": ["name"],
            },
        ),
    ]
